cookie:
  expiry_days: 30
  key: some_signature_key
  name: some_cookie_name
credentials:
  usernames:
    colbyw:
      email: colbyw@vt.edu
      failed_login_attempts: 0
      logged_in: false
      name: colbyw
      password: $2b$12$yX/fhzoBETpjrtPsb2xKgeXCoJS32T4/zPlbeRbzgGHw7.5EULI/K
      role: manager
    jsmith:
      email: jsmith@gmail.com
      failed_login_attempts: 0
      logged_in: true
      name: John Smith
      password: $2b$12$qgpdymNsKCf9Hjwg.NSXiO9/ItCdKVNoJBWQf6EAk9n73HgkAJmEC
      role: admin
    rbriggs:
      email: rbriggs@gmail.com
      failed_login_attempts: 0
      logged_in: false
      name: Rebecca Briggs
      password: $2b$12$uON60sh.2IdIk4cka2YILuRo4kQai.pU8McK/owmmJ.QawK85GrdK
      role: user
preauthorized:
  emails:
  - melsby@gmail.com
